package hospital.hospital_system.enums;

public enum PermissionEnum {
    CREATE_COMPLAINT,
    EDIT_COMPLAINT,
    DELETE_COMPLAINT,
    VIEW_COMPLAINT,

    CREATE_APPOINTMENT_RESULT,
    EDIT_APPOINTMENT_RESULT,
    DELETE_APPOINTMENT_RESULT,
    VIEW_APPOINTMENT_RESULT,

    CREATE_APPOINTMENT,
    EDIT_APPOINTMENT,
    DELETE_APPOINTMENT,
    VIEW_APPOINTMENT,

    CREATE_PATIENT,
    EDIT_PATIENT,
    DELETE_PATIENT,
    VIEW_PATIENT,

    CREATE_EMPLOYEE_ROOM,
    EDIT_EMPLOYEE_ROOM,
    DELETE_EMPLOYEE_ROOM,
    VIEW_EMPLOYEE_ROOM,

    CREATE_ROOM,
    EDIT_ROOM,
    DELETE_ROOM,
    VIEW_ROOM,

    CREATE_EMPLOYEE,
    EDIT_EMPLOYEE,
    DELETE_EMPLOYEE,
    VIEW_EMPLOYEE,

    CREATE_ATTACHMENT,
    EDIT_ATTACHMENT,
    DELETE_ATTACHMENT,
    VIEW_ATTACHMENT,

    CREATE_TURN,
    EDIT_TURN,
    DELETE_TURN,
    VIEW_TURN,

    CREATE_WORK_TIME,
    EDIT_WORK_TIME,
    DELETE_WORK_TIME,
    VIEW_WORK_TIME,

    CREATE_POSITION,
    EDIT_POSITION,
    DELETE_POSITION,
    VIEW_POSITION,

    CREATE_PERMISSION,
    EDIT_PERMISSION,
    DELETE_PERMISSION,
    VIEW_PERMISSION,

    CREATE_POSITION_PERMISSION,
    EDIT_POSITION_PERMISSION,
    DELETE_POSITION_PERMISSION,
    VIEW_POSITION_PERMISSION,
}
