spring:
  application:
    name: hospital_system
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  address: 0.0.0.0

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: swagger-ui

app:
  files:
    baseFolder: files/

jwt:
  expirationDate: 1
  secretKey: ${JWT_SECRET}